---
- name: Sample playbook
  hosts: "{{ips}}"
  become: yes
  tasks:
    - name: Update system packages
      copy: 
        src: test1.sh 
        dest: /tmp
    - name: exec
      command: bash /tmp/test1.sh 