---
- name: Sample Linux playbook
  hosts: all
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Install essential packages
      package:
        name:
          - curl
          - wget
          - vim
        state: present
    
    - name: Create a directory
      file:
        path: /tmp/example
        state: directory
        mode: '0755'
    
    - name: Copy a file
      copy:
        src: files/example.txt
        dest: /tmp/example/example.txt
        mode: '0644'