---
- name: Speed Test Playbook
  hosts: all
  gather_facts: no  # Skip fact gathering for maximum speed
  tasks:
    - name: Quick ping test
      ping:
      register: ping_result

    - name: Fast command execution
      command: echo "Speed test completed at $(date)"
      register: speed_result

    - name: System uptime check
      command: uptime
      register: uptime_result 