---
- name: Sample playbook
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install essential packages
      yum:
        name:
          - "{{package1}}"
        state: "{{status}}"
